### ISSUE TITLE
Ability to remove empty special comments?

### ISSUE THREAD

**Issue by spacedawwwg** [vitaly-t/decomment#10]
Is it possible to set up decomment to remove empty special comments?

use case is that I inject CSS and JS, but some pages do not have IE only assets.

I'd like to strip out the empty conditional comments if possible?

**Comment by vitaly-t** [comment]
At the moment this library can strip all `<!--[if` ...`-->` comments. Are you asking if it could remove only the ones that are empty?

**Comment by spacedawwwg** [comment]
Yes, just the empty ones.

**Comment by vitaly-t** [comment]
Yes, it is possible, via option [ignore](https://github.com/vitaly-t/decomment#optionsignore--regexp--regexp). You would set it to a regular expression that defines non-empty conditional blocks, so only the empty ones will be ignored.

But considering your case, are you actually removing anything else at all? Because if not, then you can do the same without decomment at all ;)

**Comment by vitaly-t** [comment]
I've started with `<!\-\-\[if[\w\-]*\](?!\s+$).*\-\->` here: https://regex101.com/ but it is not complete yet, you need to finish it yourself ;)

**Comment by spacedawwwg** [comment]
@vitaly-t Thank you.

I've got a "regex buddy" who helps me with these. I'll get him on the case for me (this is currently beyond my skill set).

**Comment by vitaly-t** [comment]
n.p. once you have the right regex, post it here, please, to share with others ;)
